### ISSUE TITLE
Double Description and missing image

### ISSUE THREAD

**Issue by geopapai** [Cardlink-SA/cardlink-payment-gateway-woocommerce#7]
Hello and thanks for the plugin.

1. The plugin gives a double description (repeating) . Cannot be edited in preferences. Look at attached image.

2. And it has a missing image (when changing payment provider it should change the image accordingly, but the code in file "class-cardlink-payment-gateway-woocommerce.php" it always points at the same image (cardlink.png):

if ( $this->acquirer == 0 ) {
			$this->icon = apply_filters( 'cardlink_icon', plugins_url() . '/cardlink-payment-gateway-woocommerce/public/img/**cardlink.png**' );
		} elseif ( $this->acquirer == 1 ) {
			$this->icon = apply_filters( 'cardlink_icon', plugins_url() . '/cardlink-payment-gateway-woocommerce/public/img/**cardlink.png**' );
		} elseif ( $this->acquirer == 2 ) {
			$this->icon = apply_filters( 'cardlink_icon', plugins_url() . '/cardlink-payment-gateway-woocommerce/public/img/**cardlink.png**' );

![2b5a24b9-c2d6-42be-b84f-93883981264f](https://github.com/Cardlink-SA/cardlink-payment-gateway-woocommerce/assets/29898457/0566419a-854e-457a-bb55-58bdc251ff98)

**Comment by spithash** [comment]
See  [here](https://github.com/Cardlink-SA/cardlink-payment-gateway-woocommerce/pull/5)

**Comment by geopapai** [comment]
OK, I will rename the folder for the moment.

Thank you for the prompt reply!
